-- Current-row source contract; do not silently deduplicate conflicting CDC rows.
select
    cast(id as varchar) as transaction_id,
    cast(user_id as varchar) as user_id,
    cast(account_id as varchar) as account_id,
    cast(type as varchar) as transaction_type,
    cast(state as varchar) as transaction_state,
    cast(sent_amount as number(38,8)) as sent_amount,
    cast(sent_currency as varchar) as sent_currency,
    cast(received_amount as number(38,8)) as received_amount,
    cast(received_currency as varchar) as received_currency,
    cast(exchange_rate as number(38,12)) as exchange_rate,
    cast(source_amount as number(38,8)) as source_amount,
    cast(recipient_id as varchar) as recipient_id,
    cast(recipient_account_id as varchar) as recipient_account_id,
    cast(workflow_id as varchar) as workflow_id,
    cast(created_at as timestamp_ntz) as created_at,
    cast(updated_at as timestamp_ntz) as updated_at,
    cast(expires_at as timestamp_ntz) as expires_at,
    cast(memo as varchar) as memo,
    cast(purpose as varchar) as purpose,
    cast(from_wallet_id as varchar) as from_wallet_id,
    cast(to_wallet_id as varchar) as to_wallet_id,
    {{ as_variant('summary') }} as summary,
    {{ as_variant('metadata') }} as metadata,
    cast(fee_label as varchar) as fee_label,
    cast(fee_kind as varchar) as fee_kind
from {{ source('payments', 'transactions_transaction') }}
